// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hospital.proto

package inventory

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hospital struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Region               string   `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Location             string   `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hospital) Reset()         { *m = Hospital{} }
func (m *Hospital) String() string { return proto.CompactTextString(m) }
func (*Hospital) ProtoMessage()    {}
func (*Hospital) Descriptor() ([]byte, []int) {
	return fileDescriptor_007177de4d78ec3e, []int{0}
}

func (m *Hospital) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hospital.Unmarshal(m, b)
}
func (m *Hospital) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hospital.Marshal(b, m, deterministic)
}
func (m *Hospital) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hospital.Merge(m, src)
}
func (m *Hospital) XXX_Size() int {
	return xxx_messageInfo_Hospital.Size(m)
}
func (m *Hospital) XXX_DiscardUnknown() {
	xxx_messageInfo_Hospital.DiscardUnknown(m)
}

var xxx_messageInfo_Hospital proto.InternalMessageInfo

func (m *Hospital) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hospital) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Hospital) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type Hospitals struct {
	Hospitals            []*Hospital `protobuf:"bytes,1,rep,name=Hospitals,proto3" json:"Hospitals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Hospitals) Reset()         { *m = Hospitals{} }
func (m *Hospitals) String() string { return proto.CompactTextString(m) }
func (*Hospitals) ProtoMessage()    {}
func (*Hospitals) Descriptor() ([]byte, []int) {
	return fileDescriptor_007177de4d78ec3e, []int{1}
}

func (m *Hospitals) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hospitals.Unmarshal(m, b)
}
func (m *Hospitals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hospitals.Marshal(b, m, deterministic)
}
func (m *Hospitals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hospitals.Merge(m, src)
}
func (m *Hospitals) XXX_Size() int {
	return xxx_messageInfo_Hospitals.Size(m)
}
func (m *Hospitals) XXX_DiscardUnknown() {
	xxx_messageInfo_Hospitals.DiscardUnknown(m)
}

var xxx_messageInfo_Hospitals proto.InternalMessageInfo

func (m *Hospitals) GetHospitals() []*Hospital {
	if m != nil {
		return m.Hospitals
	}
	return nil
}

type Response struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_007177de4d78ec3e, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Hospital)(nil), "Hospital")
	proto.RegisterType((*Hospitals)(nil), "Hospitals")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("hospital.proto", fileDescriptor_007177de4d78ec3e) }

var fileDescriptor_007177de4d78ec3e = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4b, 0xc5, 0x30,
	0x14, 0x85, 0xa9, 0xd5, 0xd2, 0x5c, 0x6b, 0x87, 0x8b, 0x48, 0xe9, 0x54, 0x8a, 0x68, 0xa7, 0x0a,
	0xd5, 0x5f, 0xe0, 0xe4, 0x28, 0x71, 0x73, 0x10, 0x52, 0x09, 0x5a, 0xa8, 0xb9, 0x21, 0x89, 0x85,
	0xf7, 0xef, 0x1f, 0x2f, 0xaf, 0x49, 0xbb, 0xe5, 0x3b, 0xe7, 0xe3, 0x90, 0x04, 0xca, 0x5f, 0xb2,
	0x7a, 0x72, 0x62, 0xee, 0xb5, 0x21, 0x47, 0x2d, 0x87, 0xfc, 0x6d, 0x4d, 0x10, 0xe1, 0x52, 0x89,
	0x3f, 0x59, 0x25, 0x4d, 0xd2, 0x31, 0xee, 0xcf, 0x78, 0x07, 0x99, 0x91, 0x3f, 0x13, 0xa9, 0xea,
	0xc2, 0xa7, 0x2b, 0x61, 0x0d, 0xf9, 0x4c, 0xdf, 0xc2, 0x9d, 0x9a, 0xd4, 0x37, 0x91, 0xdb, 0x17,
	0x60, 0x61, 0xd3, 0xe2, 0xe3, 0x0e, 0xaa, 0xa4, 0x49, 0xbb, 0xeb, 0x81, 0xf5, 0x21, 0xe1, 0x5b,
	0xd7, 0x36, 0x90, 0x73, 0x69, 0x35, 0x29, 0x2b, 0xf1, 0x16, 0xae, 0x16, 0x31, 0xff, 0x87, 0xab,
	0x9c, 0x61, 0xf8, 0x82, 0x32, 0xe8, 0x1f, 0xd2, 0x2c, 0xd2, 0xe0, 0x3d, 0x14, 0xef, 0x64, 0x5d,
	0x7c, 0xc1, 0xb6, 0x5c, 0xb3, 0x3e, 0xae, 0x3d, 0xc0, 0xcd, 0xde, 0xb2, 0x08, 0x51, 0xb3, 0x3b,
	0xef, 0xb5, 0xfc, 0x2c, 0xf4, 0xf8, 0x34, 0xa9, 0x45, 0x2a, 0x47, 0xe6, 0x30, 0x66, 0xfe, 0x8b,
	0x9e, 0x8f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xe6, 0x2b, 0x81, 0x34, 0x01, 0x00, 0x00,
}
